apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-scheduler
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-scheduler
  template:
    metadata:
      labels:
        app: backend-scheduler
    spec:
      containers:
        - name: backend-scheduler
          image: mohamedzahran1989/python-nodejs:python3.8-nodejs14
          workingDir: /server
          ports:
            - name: backend-port
              containerPort: 3030
            - name: bind-https-port
              containerPort: 443
          env:
            - name: MONGO_DB_URL
              value: "mongodb://mongodb-service.default.svc.cluster.local:27017/ueyedata"  # will be changed while deployment with the new DB service IP
            - name: NSQ_HOST
              value: "nsq-service.default.svc.cluster.local" # will be changed while deployment with the new NSQ service IP
            - name: NSQ_TCP_PORT
              value: "4150"
            - name: LOGGING_LEVEL
              value: "verbose"
            - name: ACCESS_LOG
              value: "true"
            - name: SSL
              value: "true"
            - name: LOG_CONTEXT
              value: "false"
            - name: SENTIMENT_SERVER
              value: "http://umbra1-sentiment-service.default.svc.cluster.local:5000/get_sentiment"
            - name: CONTAINER_NAME
              value: "backend-service-clusterip.default.svc.cluster.local"
            - name: worker_node
              value: "ec2-54-173-23-135.compute-1.amazonaws.com"
            - name: SUPPORTED_LANGUAGES
              value: "en, ar"
            - name: VENDOR
              value: "octaeye"
            - name: DOCX_CONVERTER_SERVER
              value: "http://pdfconverter-service.default.svc.cluster.local:3032"
            - name: SOCIAL_ANALYTICS_API_ID
              value: "1001_O"
            - name: SOCIAL_ANALYTICS_API_KEY
              value: "999hgXppWUlouwasIGLpWiuR+TkctVkLyI3WarMF0bA="
            - name: SOCIAL_ANALYTICS_URL
              value: "https://umbrasys.ddns.net:3035"
            - name: FB_DATA_SEARCH_API_ID
              value: "1001_O"
            - name: FB_DATA_SEARCH_API_KEY
              value: "999hgXppWUlouwasIGLpWiuR+TkctVkLyI3WarMF0bA="
            - name: FB_DATA_SEARCH_URL
              value: "https://umbrasys.ddns.net:3036"
            - name: FB_DATA_SEARCH_COUNTRIES
              value: "Egypt"
            - name: TRENDING_SEARCH_API_ID
              value: "1001_O"
            - name: TRENDING_SEARCH_API_KEY
              value: "999hgXppWUlouwasIGLpWiuR+TkctVkLyI3WarMF0bA="
            - name: TRENDING_SEARCH_URL
              value: "https://umbrasys.ddns.net:3037"
            - name: APP2FACTOR_AUTH_URL
              value: "http://umbrasys.ddns.net:5100/api/auth_code/"
            - name: disable_nsq
              value: "false"
            - name: roles
              value: "migrations, scheduler"
            - name: INSTANCE
              value: "main-app-scheduler"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
              - name: backend-code-volume
                mountPath: "/server"
          command: ["yarn", "start"]
      volumes:
        - name: backend-code-volume
          persistentVolumeClaim:
            claimName: backend-code-pvc

      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
        
      imagePullSecrets:
      - name: myregistrykey
