apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-python-deployment
  labels:
    app: kube-python
spec:
  replicas: 50
  selector:
    matchLabels:
      app: kube-python
  template:
    metadata:
      labels:
        app: kube-python
    spec:
      containers:
      - name: kube-python
        image: mohamedzahran1989/kpythonnew:new1
        imagePullPolicy: Always
        env:
        - name: NFS_SERVER_IP
          value: "172.31.89.131"  # Replace with your NFS server IP
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: nfs-storage
          mountPath: /app/nfs
      volumes:
      - name: data-volume
        hostPath:
          path: /data 
          type: DirectoryOrCreate
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      imagePullSecrets:
      - name: myregistrykey
