
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scheduler-code-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs/server
    server: 172.31.89.131
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scheduler-code-pv
spec:
  volumeName: scheduler-code-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
