apiVersion: apps/v1
kind: Deployment
metadata:
  name: umbra1-sentiment-deployment
  labels:
    app: umbra1-sentiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umbra1-sentiment
  template:
    metadata:
      labels:
        app: umbra1-sentiment
    spec:
      containers:
      - name: umbra1-sentiment-container
        image: mohamedzahran1989/umbra1_sentiment:latest
